"""Add shared emergency fields to patient model

Revision ID: 421113e3051b
Revises: 457bad520750
Create Date: 2025-10-28 09:24:38.579253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421113e3051b'
down_revision = '457bad520750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_profiles', schema=None) as batch_op:
        batch_op.drop_column('next_of_kin_phone')
        batch_op.drop_column('next_of_kin_name')
        batch_op.drop_column('allergies')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_aid_procedure', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('caregiver_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('caregiver_phone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('caregiver_phone')
        batch_op.drop_column('caregiver_name')
        batch_op.drop_column('next_of_kin_phone')
        batch_op.drop_column('next_of_kin_name')
        batch_op.drop_column('allergies')
        batch_op.drop_column('first_aid_procedure')

    with op.batch_alter_table('emergency_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allergies', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
