"""Add password field to doctor

Revision ID: 457bad520750
Revises: a04ec96a5983
Create Date: 2025-10-27 10:31:50.281196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457bad520750'
down_revision = 'a04ec96a5983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
