"""caregiver to get remainders to

Revision ID: a04ec96a5983
Revises: e7a863214d57
Create Date: 2025-10-23 16:43:42.159646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04ec96a5983'
down_revision = 'e7a863214d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caregiver_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'caregivers', ['caregiver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('caregiver_id')

    # ### end Alembic commands ###
