"""Add public_id and consent fields to EmergencyProfile

Revision ID: e7a863214d57
Revises: b253bc115f37
Create Date: 2025-10-23 16:34:27.208911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a863214d57'
down_revision = 'b253bc115f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('public_visible', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('public_phone_visible', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['public_id'])
        batch_op.create_unique_constraint(None, ['qr_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('public_phone_visible')
        batch_op.drop_column('public_visible')
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
